apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: notejam:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http

