apiVersion: v1
kind: ConfigMap
metadata:
  name: root
  namespace: default
  labels:
    app.kubernetes.io/name: root
    app.kubernetes.io/part-of: default
data:
  repositories: |
    - url: https://github.com/Calculus8303/argotest.git
      type: git
      fetchInterval: "30"
