apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/Calculus8303/argotest.git
    targetRevision: HEAD
    pollInterval: 1m
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
