apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    name: metrics-server
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/  
    targetRevision: "3.10.0"  
    path: metrics-server  
    helm:
      passCredentials: false 
      parameters:
        - name: args
          value: "--kubelet-insecure-tls --secure-port=6443 --cert-dir=/tmp"
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
