apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: kube-system
  spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    helm:
      parameters:
      - name: args
        value: '{--kubelet-insecure-tls}'
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
