apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notejam
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/notejam
    repoURL: https://github.com/Calculus8303/argotest.git  # Replace "your-username" with your GitHub username
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
