apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cli-container
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: /dev/null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
  spec:
    destination:
      namespace: default
    project: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - Validate=false
    template:
      metadata:
        labels:
          app: aws-cli-container
      spec:
        containers:
          - name: aws-cli-container
            image: amazon/aws-cli
            command: ["/bin/sh", "-c"]
            args:
              - |
                #!/bin/sh
                aws s3 ls s3://pavlo.n-bucket
