apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notejam-1
spec:
  serviceName: notejam
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      hostname: notejam
      serviceAccount: notejam
      containers:
      - name: notejam
        image: notejam:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: local-storage
          mountPath: /app/database
  volumeClaimTemplates:
  - metadata:
      name: local-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
