apiVersion: v1
kind: ServiceAccount
metadata:
  name: notejam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notejam
subjects:
- kind: ServiceAccount
  name: notejam
  namespace: default
roleRef:
  kind: Role
  name: notejam
  apiGroup: rbac.authorization.k8s.io
