argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
  controller:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
  redis:
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
